### ISSUE TITLE
.PLY content/fields.  Error with no RGB in ply

### ISSUE THREAD

**Issue by bj-neilson** [saeedghsh/Mesh-To-Occupancy-Map#2]
Hi @saeedghsh 

Thanks for sharing this package!  Trying to give it a run.  

**I have both packages sitting under common directory:**

ben@ben-Aspire:~/mesh-to-map$ ls
Mesh-To-Occupancy-Map  Place-Categorization-2D

**When running:** 

python mesh_to_ogm_v2.py -s -v --filename /home/ben/Documents/Wildcat/2022_08_31_00_07_24Z/output/global_wildcat_velodyne.ply

**Result is:**

Traceback (most recent call last):
  File "mesh_to_ogm_v2.py", line 123, in <module>
    main (filename, slice_config, ogm_config, raycast_config)
  File "mesh_to_ogm_v2.py", line 54, in main
    ply_data, faces, [Vx, Vy, Vz, Vr, Vg, Vb, Va] = convert_mesh.load_ply_file ( file_name )
  File "../lib/convert_mesh.py", line 78, in load_ply_file
    Vr = ply_data['vertex'].data['red'] # u1 -> usigned int 8
  File "/home/ben/.local/lib/python2.7/site-packages/numpy/core/memmap.py", line 331, in __getitem__
    res = super(memmap, self).__getitem__(index)
ValueError: no field of name red

**Is this because i have no data in the RGB fields in my ply?  would you mind posting a demo .ply that i can test with?**

Thanks heaps,
Ben

**Comment by saeedghsh** [comment]
Hello @bj-neilson ,

I haven't tested this code in ages, so not sure what exactly is wrong. My guess is similar to yours regarding the rgb-values. And regarding sample ply files, you can find some here:

https://github.com/saeedghsh/Halmstad-Robot-Maps/

**Comment by bj-neilson** [comment]
Thanks @saeedghsh. Appreciate you taking the time to answer.  I'll grab that sample data and compare.  Never knew it could be so hard to take a point cloud, (even with a trajectory as well from recording it) and generate a 2D occupancy grid at ground level!

**Comment by saeedghsh** [comment]
Yeah, it can be quite tricky to convert a 3D point cloud into 2D occupancy map, specially in cluttered environments! This can get complicated rather fast.

Of course if your are willing to go for it, you can build a mapping pipeline and build the 2D occupancy directly from 3D scans. I didn't want to bother and wanted to take advantage of the best available SLAM out there, so I did so and converted the resulting map to 2D. Although, building 2D map from 3D point cloud scans is not that straightforward either.

My approach has been, IIRC, to use off the shelf SLAM to get a map from scans, and then
* take few layers of the 3D point cloud (the compiled map, not just a single scans) at different height,
* do few iteration of a mix between filtering and consensus among the different layers which resulted in a binary occupancy [1],
* then an [interactive] ray casting, i.e. take the binary occupancy and "simulate" a range scanner (like LiDAR) and distinguish the open space from unexplored [2].

[1]  which captures the occupancy, but can't tell open space from unexplored area.
[2] The interactive part is to pick the place to ray cast from, i.e. few points in the open space. But this could easily be replaced with points on the trajectory that sensor took. I collected my maps with Google tango tablets which did not provide the trajectory readily, so I had to do it interactively.

PS: I will go ahead and close this issue. Feel free to re-open it if you have any further question.
